In [1]:
import gc
import os
import matplotlib.pyplot as plt
import numpy as np
import polars as pl
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # suppress CUDA errors
import tensorflow as tf
from keras import mixed_precision, utils, layers, saving, losses, optimizers, metrics, callbacks, Sequential
from sklearn import model_selection

mixed_precision.set_global_policy('mixed_float16') # https://keras.io/2/api/mixed_precision/policy/
utils.set_random_seed(42)

In [2]:
data = pl.read_csv('train.csv').drop('date_id').with_columns(
    pl.all().cast(pl.Float64, strict=False),
    pl.col('forward_returns').shift(-1).alias('lagged_forward_returns'),
    pl.col('risk_free_rate').shift(-1).alias('lagged_risk_free_rate'),
    pl.col('market_forward_excess_returns').shift(-1).alias('lagged_market_forward_excess_returns'),
).fill_null(0)
data

shape: (8_990, 100)
┌─────┬─────┬─────┬─────┬───┬─────────────────┬─────────────────┬─────────────────┬────────────────┐
│ D1  ┆ D2  ┆ D3  ┆ D4  ┆ … ┆ market_forward_ ┆ lagged_forward_ ┆ lagged_risk_fre ┆ lagged_market_ │
│ --- ┆ --- ┆ --- ┆ --- ┆   ┆ excess_returns  ┆ returns         ┆ e_rate          ┆ forward_excess │
│ f64 ┆ f64 ┆ f64 ┆ f64 ┆   ┆ ---             ┆ ---             ┆ ---             ┆ _r…            │
│     ┆     ┆     ┆     ┆   ┆ f64             ┆ f64             ┆ f64             ┆ ---            │
│     ┆     ┆     ┆     ┆   ┆                 ┆                 ┆                 ┆ f64            │
╞═════╪═════╪═════╪═════╪═══╪═════════════════╪═════════════════╪═════════════════╪════════════════╡
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ … ┆ -0.003038       ┆ -0.008495       ┆ 0.000303        ┆ -0.009114      │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ … ┆ -0.009114       ┆ -0.009624       ┆ 0.000301        ┆ -0.010243      │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ … ┆ -0.010243       ┆ 0.004662        ┆ 0.000299        ┆ 0.004046       │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ … ┆ 0.004046        ┆ -0.011686       ┆ 0.000299        ┆ -0.012301      │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ … ┆ -0.012301       ┆ -0.006449       ┆ 0.0003          ┆ -0.007066      │
│ …   ┆ …   ┆ …   ┆ …   ┆ … ┆ …               ┆ …               ┆ …               ┆ …              │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.00199         ┆ 0.002312        ┆ 0.000156        ┆ 0.001845       │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.001845        ┆ 0.002891        ┆ 0.000156        ┆ 0.002424       │
│ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ … ┆ 0.002424        ┆ 0.00831         ┆ 0.000156        ┆ 0.007843       │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.007843        ┆ 0.000099        ┆ 0.000156        ┆ -0.000368      │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ -0.000368       ┆ 0.0             ┆ 0.0             ┆ 0.0            │
└─────┴─────┴─────┴─────┴───┴─────────────────┴─────────────────┴─────────────────┴────────────────┘

In [3]:
targets = np.where(data['forward_returns'] > data['risk_free_rate'], 1.0, 0.0)
targets

array([0., 0., 0., ..., 1., 1., 0.], shape=(8990,))

In [4]:
inputs = data.drop(['forward_returns', 'risk_free_rate', 'market_forward_excess_returns']).to_numpy()
inputs

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -8.49467704e-03,  3.02777778e-04, -9.11404562e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -9.62447844e-03,  3.01190476e-04, -1.02425375e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         4.66239748e-03,  2.99206349e-04,  4.04620350e-03],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, ...,
         8.31020684e-03,  1.55952381e-04,  7.84287397e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         9.88397731e-05,  1.55873016e-04, -3.68167698e-04],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],
      shape=(8990, 97))

In [23]:
@saving.register_keras_serializable('hull-tactical-market-prediction', name='hull_composite_loss')
def hull_composite_loss(y_true, y_pred):
    penalties = [
        losses.binary_crossentropy(y_true, y_pred, from_logits=True, label_smoothing=0.4),
        tf.reduce_mean(tf.maximum(0.0, y_pred - y_true)), # punishes false positives
        tf.reduce_mean(tf.maximum(0.0, y_true - y_pred)), # punishes false negatives
        tf.reduce_mean(tf.square(tf.maximum(0.0, -y_pred))), # punishes values below 0
        tf.reduce_mean(tf.square(tf.maximum(0.0, y_pred - 1.0))), # punishes values above 1
    ]
    return sum(penalties)

In [24]:
N_FEATURES = inputs.shape[-1]
N_FEATURES

97

In [25]:
model = Sequential([
    layers.Input([N_FEATURES]),
    layers.Dropout(0.1),
    layers.BatchNormalization(),
    layers.Dense(N_FEATURES),
    layers.Dropout(0.1),
    layers.BatchNormalization(),
    layers.Dense(int(2 * N_FEATURES // 3)),
    layers.Dropout(0.1),
    layers.BatchNormalization(),
    layers.Dense(1, activation='sigmoid')
], name='v21')

model.compile(loss=hull_composite_loss, optimizer=optimizers.Adamax(), metrics=[metrics.MeanAbsoluteError()])

In [26]:
for k, (i_train, i_val) in enumerate(model_selection.TimeSeriesSplit().split(inputs)):
    model.fit(inputs[i_train], targets[i_train], epochs=1000, validation_data=(inputs[i_val], targets[i_val]), #verbose=0,
              callbacks=[callbacks.EarlyStopping(patience=20, restore_best_weights=True), callbacks.TerminateOnNaN()])
    model.save(f'.models/{model.name}.keras')
    while gc.collect() > 0: pass

Epoch 1/1000
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - loss: 1.2201 - mean_absolute_error: 0.4985 - val_loss: 1.2146 - val_mean_absolute_error: 0.4869
Epoch 2/1000
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2034 - mean_absolute_error: 0.4872 - val_loss: 1.2112 - val_mean_absolute_error: 0.4830
Epoch 3/1000
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1930 - mean_absolute_error: 0.4794 - val_loss: 1.2076 - val_mean_absolute_error: 0.4809
Epoch 4/1000
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1886 - mean_absolute_error: 0.4768 - val_loss: 1.2067 - val_mean_absolute_error: 0.4782
Epoch 5/1000
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1829 - mean_absolute_error: 0.4724 - val_loss: 1.2039 - val_mean_absolute_error: 0.4786
Epoch 6/1000
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1831 - mean_absolute_error: 0.4725 - val_loss: 1.2043 - val_mean_absolute_error: 0.4781
Epoch 7/1000
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1747 - mean_absolute_error: 0.4652 - 

In [27]:
test_data = pl.read_csv('test.csv').drop(['date_id', 'is_scored']).fill_null(0)
test_data

shape: (10, 97)
┌─────┬─────┬─────┬─────┬───┬───────────┬───────────────────┬───────────────────┬──────────────────┐
│ D1  ┆ D2  ┆ D3  ┆ D4  ┆ … ┆ V9        ┆ lagged_forward_re ┆ lagged_risk_free_ ┆ lagged_market_fo │
│ --- ┆ --- ┆ --- ┆ --- ┆   ┆ ---       ┆ turns             ┆ rate              ┆ rward_excess_r…  │
│ i64 ┆ i64 ┆ i64 ┆ i64 ┆   ┆ f64       ┆ ---               ┆ ---               ┆ ---              │
│     ┆     ┆     ┆     ┆   ┆           ┆ f64               ┆ f64               ┆ f64              │
╞═════╪═════╪═════╪═════╪═══╪═══════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.751909 ┆ 0.003541          ┆ 0.000161          ┆ 0.003068         │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.660326 ┆ -0.005964         ┆ 0.000162          ┆ -0.006437        │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.510979 ┆ -0.00741          ┆ 0.00016           ┆ -0.007882        │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.575997 ┆ 0.00542           ┆ 0.00016           ┆ 0.004949         │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.654045 ┆ 0.008357          ┆ 0.000159          ┆ 0.007887         │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.649616 ┆ -0.002896         ┆ 0.000159          ┆ -0.003365        │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.668289 ┆ 0.002457          ┆ 0.000155          ┆ 0.00199          │
│ 0   ┆ 0   ┆ 1   ┆ 0   ┆ … ┆ -0.670946 ┆ 0.002312          ┆ 0.000156          ┆ 0.001845         │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.646265 ┆ 0.002891          ┆ 0.000156          ┆ 0.002424         │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ -0.705662 ┆ 0.00831           ┆ 0.000156          ┆ 0.007843         │
└─────┴─────┴─────┴─────┴───┴───────────┴───────────────────┴───────────────────┴──────────────────┘

In [28]:
test_targets = np.where(test_data['lagged_market_forward_excess_returns'].shift(1) > 0, 1.0, 0.0)
test_targets

array([0., 1., 0., 0., 1., 1., 0., 1., 1., 1.])

In [29]:
test_inputs = test_data.to_numpy()
test_inputs.shape

(10, 97)

In [30]:
plt.figure(figsize=(13, 5))
plt.title(f'{model.name} Signals vs Hull Targets')
plt.plot(test_targets, zorder=-1)
indices = np.arange(test_targets.shape[0])
plt.scatter(indices, test_targets, label='Target', edgecolors='k', c='g', s=64)
signals = model.predict(test_inputs)
plt.plot(signals, zorder=-1)
plt.scatter(indices, signals, label='Signal', marker='X', edgecolors='k', c='r', s=64)
plt.legend()
pass

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step


In [31]:
signals

array([[0.0007825],
       [0.03955  ],
       [0.4346   ],
       [0.001121 ],
       [0.3843   ],
       [0.02406  ],
       [0.004436 ],
       [0.4524   ],
       [0.07935  ],
       [0.006264 ]], dtype=float16)